CREATE TABLE atendente( 
      id  integer generated by default as identity     NOT NULL , 
      system_user_id integer    NOT NULL , 
 PRIMARY KEY (id)) ; 

CREATE TABLE atendimento( 
      id  integer generated by default as identity     NOT NULL , 
      tipo_atendimento_id integer    NOT NULL , 
      setor_id integer    NOT NULL , 
      cliente_id integer    NOT NULL , 
      cliente_usuario_id integer    NOT NULL , 
      atendente_id integer   , 
      arquivos blob sub_type 1   , 
      data_abertura timestamp   , 
      data_fechamento timestamp   , 
      mensagem blob sub_type 1   , 
 PRIMARY KEY (id)) ; 

CREATE TABLE atendimento_interacao( 
      id  integer generated by default as identity     NOT NULL , 
      atendimento_id integer    NOT NULL , 
      atendente_id integer   , 
      cliente_usuario_id integer   , 
      arquivos blob sub_type 1   , 
      mensagem blob sub_type 1   , 
      data_interacao timestamp   , 
 PRIMARY KEY (id)) ; 

CREATE TABLE categoria_guia( 
      id  integer generated by default as identity     NOT NULL , 
      nome blob sub_type 1    NOT NULL , 
 PRIMARY KEY (id)) ; 

CREATE TABLE cliente( 
      id  integer generated by default as identity     NOT NULL , 
      nome blob sub_type 1    NOT NULL , 
      email blob sub_type 1   , 
      telefone blob sub_type 1   , 
 PRIMARY KEY (id)) ; 

CREATE TABLE cliente_usuario( 
      id  integer generated by default as identity     NOT NULL , 
      cliente_id integer    NOT NULL , 
      system_user_id integer   , 
      ativo char  (1)   , 
 PRIMARY KEY (id)) ; 

CREATE TABLE documento( 
      id  integer generated by default as identity     NOT NULL , 
      cliente_id integer    NOT NULL , 
      tipo_documento_id integer    NOT NULL , 
      created_by_system_user_id integer   , 
      vaildade date   , 
      arquivo blob sub_type 1   , 
      observacao blob sub_type 1   , 
 PRIMARY KEY (id)) ; 

CREATE TABLE documento_download_log( 
      id  integer generated by default as identity     NOT NULL , 
      documento_id integer    NOT NULL , 
      downloaded_by_system_user_id integer    NOT NULL , 
      data_download timestamp    NOT NULL , 
 PRIMARY KEY (id)) ; 

CREATE TABLE fila_email( 
      id  integer generated by default as identity     NOT NULL , 
      fila_email_status_id integer    NOT NULL , 
      titulo blob sub_type 1    NOT NULL , 
      conteudo blob sub_type 1    NOT NULL , 
      arquivos blob sub_type 1   , 
      destinatarios blob sub_type 1    NOT NULL , 
      tentativas_envio integer   , 
      tipo_origem blob sub_type 1   , 
      erro blob sub_type 1   , 
      data_envio timestamp   , 
      criado_em timestamp   , 
 PRIMARY KEY (id)) ; 

CREATE TABLE fila_email_status( 
      id  integer generated by default as identity     NOT NULL , 
      nome blob sub_type 1    NOT NULL , 
 PRIMARY KEY (id)) ; 

CREATE TABLE guia( 
      id  integer generated by default as identity     NOT NULL , 
      subcategoria_guia_id integer    NOT NULL , 
      cliente_id integer    NOT NULL , 
      created_by_system_user_id integer    NOT NULL , 
      ano_competencia integer    NOT NULL , 
      mes_competencia integer    NOT NULL , 
      data_vencimento date    NOT NULL , 
      download_pos_vencimento char  (1)    DEFAULT 'F'  NOT NULL , 
      arquivo blob sub_type 1    NOT NULL , 
      downloaded char  (1)    DEFAULT 'F'  NOT NULL , 
 PRIMARY KEY (id)) ; 

CREATE TABLE guia_download_log( 
      id  integer generated by default as identity     NOT NULL , 
      guia_id integer    NOT NULL , 
      downloaded_by_system_user_id integer    NOT NULL , 
      data_download timestamp    NOT NULL , 
 PRIMARY KEY (id)) ; 

CREATE TABLE link_util( 
      id  integer generated by default as identity     NOT NULL , 
      created_by_system_user_id integer    NOT NULL , 
      titulo blob sub_type 1    NOT NULL , 
      descricao blob sub_type 1    NOT NULL , 
      link blob sub_type 1    NOT NULL , 
      ativo char  (1)    DEFAULT 'T'  NOT NULL , 
      criado_em timestamp    NOT NULL , 
 PRIMARY KEY (id)) ; 

CREATE TABLE noticia( 
      id  integer generated by default as identity     NOT NULL , 
      created_by_system_user_id integer    NOT NULL , 
      titulo blob sub_type 1    NOT NULL , 
      descricao_resumida blob sub_type 1    NOT NULL , 
      conteudo blob sub_type 1    NOT NULL , 
      foto_capa blob sub_type 1    NOT NULL , 
      data_noticia timestamp    NOT NULL , 
      ativo char  (1)    NOT NULL , 
 PRIMARY KEY (id)) ; 

CREATE TABLE pagina_conhecimento( 
      id  integer generated by default as identity     NOT NULL , 
      created_by_system_user_id integer    NOT NULL , 
      titulo blob sub_type 1    NOT NULL , 
      conteudo blob sub_type 1    NOT NULL , 
      descricao_resumida blob sub_type 1    NOT NULL , 
      ativo char  (1)    DEFAULT 'T'  NOT NULL , 
 PRIMARY KEY (id)) ; 

CREATE TABLE setor( 
      id  integer generated by default as identity     NOT NULL , 
      nome blob sub_type 1    NOT NULL , 
 PRIMARY KEY (id)) ; 

CREATE TABLE setor_atendente( 
      id  integer generated by default as identity     NOT NULL , 
      setor_id integer    NOT NULL , 
      atendente_id integer    NOT NULL , 
 PRIMARY KEY (id)) ; 

CREATE TABLE subcategoria_guia( 
      id  integer generated by default as identity     NOT NULL , 
      nome blob sub_type 1    NOT NULL , 
      categoria_guia_id integer    NOT NULL , 
 PRIMARY KEY (id)) ; 

CREATE TABLE template_email( 
      id  integer generated by default as identity     NOT NULL , 
      nome blob sub_type 1    NOT NULL , 
      titulo blob sub_type 1    NOT NULL , 
      conteudo blob sub_type 1    NOT NULL , 
 PRIMARY KEY (id)) ; 

CREATE TABLE tipo_atendimento( 
      id  integer generated by default as identity     NOT NULL , 
      nome blob sub_type 1    NOT NULL , 
 PRIMARY KEY (id)) ; 

CREATE TABLE tipo_documento( 
      id  integer generated by default as identity     NOT NULL , 
      nome blob sub_type 1    NOT NULL , 
 PRIMARY KEY (id)) ; 

 
  
 ALTER TABLE atendimento ADD CONSTRAINT fk_atendimento_1 FOREIGN KEY (tipo_atendimento_id) references tipo_atendimento(id); 
ALTER TABLE atendimento ADD CONSTRAINT fk_atendimento_2 FOREIGN KEY (setor_id) references setor(id); 
ALTER TABLE atendimento ADD CONSTRAINT fk_atendimento_3 FOREIGN KEY (cliente_id) references cliente(id); 
ALTER TABLE atendimento ADD CONSTRAINT fk_atendimento_4 FOREIGN KEY (atendente_id) references atendente(id); 
ALTER TABLE atendimento ADD CONSTRAINT fk_atendimento_5 FOREIGN KEY (cliente_usuario_id) references cliente_usuario(id); 
ALTER TABLE atendimento_interacao ADD CONSTRAINT fk_atendimento_interacao_1 FOREIGN KEY (atendimento_id) references atendimento(id); 
ALTER TABLE atendimento_interacao ADD CONSTRAINT fk_atendimento_interacao_2 FOREIGN KEY (atendente_id) references atendente(id); 
ALTER TABLE atendimento_interacao ADD CONSTRAINT fk_atendimento_interacao_3 FOREIGN KEY (cliente_usuario_id) references cliente_usuario(id); 
ALTER TABLE cliente_usuario ADD CONSTRAINT fk_cliente_usuario_1 FOREIGN KEY (cliente_id) references cliente(id); 
ALTER TABLE documento ADD CONSTRAINT fk_documento_1 FOREIGN KEY (cliente_id) references cliente(id); 
ALTER TABLE documento ADD CONSTRAINT fk_documento_2 FOREIGN KEY (tipo_documento_id) references tipo_documento(id); 
ALTER TABLE documento_download_log ADD CONSTRAINT fk_documento_download_log_1 FOREIGN KEY (documento_id) references documento(id); 
ALTER TABLE fila_email ADD CONSTRAINT fk_fila_email_1 FOREIGN KEY (fila_email_status_id) references fila_email_status(id); 
ALTER TABLE guia ADD CONSTRAINT fk_guia_1 FOREIGN KEY (subcategoria_guia_id) references subcategoria_guia(id); 
ALTER TABLE guia ADD CONSTRAINT fk_guia_2 FOREIGN KEY (cliente_id) references cliente(id); 
ALTER TABLE guia_download_log ADD CONSTRAINT fk_guia_download_log_1 FOREIGN KEY (guia_id) references guia(id); 
ALTER TABLE setor_atendente ADD CONSTRAINT fk_setor_atendente_1 FOREIGN KEY (setor_id) references setor(id); 
ALTER TABLE setor_atendente ADD CONSTRAINT fk_setor_atendente_2 FOREIGN KEY (atendente_id) references atendente(id); 
ALTER TABLE subcategoria_guia ADD CONSTRAINT fk_subcategoria_guia_1 FOREIGN KEY (categoria_guia_id) references categoria_guia(id); 
